<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://xmlns.heb.com/ei/OrderResponse" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://xmlns.heb.com/ei/OrderRequest" xmlns:tns="http://xmlns.example.com/1426881872020" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1426881872020">
    <import namespace="http://xmlns.heb.com/ei/OrderRequest" location="../Schema Definitions/Custom/OrderRequest.xsd"/>
    <import namespace="http://xmlns.heb.com/ei/OrderResponse" location="../Schema Definitions/Custom/OrderReplay.xsd"/>
    <message name="Request">
        <part name="Request" element="ns:OrderRequest"/>
    </message>
    <message name="Replay">
        <part name="Replay" element="ns2:OrderResponse"/>
    </message>
    <portType name="MagentoToPosService">
        <operation name="Operation">
            <input message="tns:Request"/>
            <output message="tns:Replay"/>
        </operation>
    </portType>
</definitions>