INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO', 'IntegracionesTIBCO@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('SOPORTE SHOPPING', 'SShoppingExp@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('SOPORTE MERCHANDISING', 'SMerchandising@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('SOPORTE ENABLING', 'SEnabling@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('SOPORTE SUPPLY CHAIN', 'SSupplyChain@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('OPERADOR DE SISTEMA', 'OperSys@hebmex.com');

INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('TECHNICAL-ERROR', 'SCI201097-PmmPOPublisher');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('FUNCTIONAL-ERROR', 'SCI201097-PmmPOPublisher');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('DATA-ERROR', 'SCI201097-PmmPOPublisher');

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 1)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (6, 1)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 2)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (2, 2)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (3, 2)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (4, 2)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 3)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (3, 3)

INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('TECHNICAL-ERROR', 'SCI201097-PmmPOSubscriber-1');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('FUNCTIONAL-ERROR', 'SCI201097-PmmPOSubscriber-1');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('DATA-ERROR', 'SCI201097-PmmPOSubscriber-1');

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 4)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (6, 4)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 5)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (2, 5)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (3, 5)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (4, 5)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 6)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (3, 6)

INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('TECHNICAL-ERROR', 'SCI201097-PmmPOSubscriber-SXD201001-1');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('FUNCTIONAL-ERROR', 'SCI201097-PmmPOSubscriber-SXD201001-1');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('DATA-ERROR', 'SCI201097-PmmPOSubscriber-SXD201001-1');

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 7)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (6, 7)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 8)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (2, 8)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (3, 8)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (4, 8)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 9)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (3, 9)

INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('TECHNICAL-ERROR', 'SCI201097-PmmToExe-PODemandPublisher');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('FUNCTIONAL-ERROR', 'SCI201097-PmmToExe-PODemandPublisher');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('DATA-ERROR', 'SCI201097-PmmToExe-PODemandPublisher');

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 10)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (6, 10)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 11)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (2, 11)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (3, 11)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (4, 11)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 12)
INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (3, 12)