USE [DBFINSYS]
GO

/****** Object:  Table [dbo].[HEB_COMPRASYRENDIMIENTOS_DET]    Script Date: 21/08/2017 10:56:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HEB_COMPRASYRENDIMIENTOS_DET](
	[PROCESS_DATE] [datetime] NOT NULL,
	[ORG_LVL_NUMBER] [decimal](12, 0) NOT NULL,
	[PRD_LVL_NUMBER_5] [nchar](15) NOT NULL,
	[PRD_LVL_NUMBER_4] [nchar](15) NOT NULL,
	[TRANS_HM_EXT_RETAIL] [decimal](14, 3) NULL,
	[TRANS_HM_EXT_COST] [decimal](14, 3) NULL,
	[DOWNLOAD_DATE_1] [datetime] NOT NULL,
	[DOWNLOAD_DATE_2] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PROCESS_DATE] ASC,
	[ORG_LVL_NUMBER] ASC,
	[PRD_LVL_NUMBER_5] ASC,
	[DOWNLOAD_DATE_1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 94) ON [PRIMARY]
) ON [PRIMARY]

GO