INSERT INTO DBSTG_INT..INT_STORES (STOREID, DESCRIPTION, URL) VALUES (2953, 'HEB HACIENDA LOS MORALES','jdbc:sqlserver://DB_LAFE:5000')
INSERT INTO DBSTG_INT..INT_STORES (STOREID, DESCRIPTION, URL) VALUES (2920, 'MI TIENDA ZUAZUA','jdbc:sqlserver://srd292001:5000')
INSERT INTO DBSTG_INT..INT_STORES (STOREID, DESCRIPTION, URL) VALUES (2974, 'HEB ESCOBEDO','jdbc:sqlserver://srd297401:5000')
