INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; jagundis@hebmex.com; aveliz@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; jagundis@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; jesus.agundis@softtek.com ; aveliz@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; aveliz@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; armando.veliz@softtek.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; armando.veliz@softtek.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; omartinez2@hebmex.com; aveliz@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; octavio.martinez@softtek.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; octavio.martinez@softtek.com; aveliz@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; rleal@hebmex.com ; aveliz@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; rleal@hebmex.com');
INSERT INTO DBSDI.DBO.TIB_USER (NAME, EMAIL) VALUES ('INTEGRACIONES TIBCO, COMITE QA', 'cduarte@hebmex.com; lcastor@hebmex.com; rleal@hebmex.com ; aveliz@hebmex.com');

INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('TECHNICAL-ERROR', 'SCI201097-PmmPOPublisher');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('FUNCTIONAL-ERROR', 'SCI201097-PmmPOPublisher');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('DATA-ERROR', 'SCI201097-PmmPOPublisher');

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (1, 1)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (2, 2)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (3, 3)


INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('TECHNICAL-ERROR', 'SCI201097-PmmPOSubscriber-1');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('FUNCTIONAL-ERROR', 'SCI201097-PmmPOSubscriber-1');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('DATA-ERROR', 'SCI201097-PmmPOSubscriber-1');

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (4, 4)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (5, 5)


INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (6, 6)


INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('TECHNICAL-ERROR', 'SCI201097-PmmPOSubscriber-SXD201001-1');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('FUNCTIONAL-ERROR', 'SCI201097-PmmPOSubscriber-SXD201001-1');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('DATA-ERROR', 'SCI201097-PmmPOSubscriber-SXD201001-1');

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (7, 7)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (8, 8)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (9, 9)


INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('TECHNICAL-ERROR', 'SCI201097-PmmToExe-PODemandPublisher');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('FUNCTIONAL-ERROR', 'SCI201097-PmmToExe-PODemandPublisher');
INSERT INTO DBSDI.DBO.TIB_GROUP (GROUP_NAME, PROJECT_NAME) VALUES ('DATA-ERROR', 'SCI201097-PmmToExe-PODemandPublisher');

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (10, 10)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (11, 11)

INSERT INTO DBSDI.DBO.TIB_USER_GROUP (ID_USER, ID_GROUP) VALUES (12, 12)
